apiVersion: v1
kind: Service
metadata:
  name: ms-usuariocliente
  namespace: backend
    #agregar esto a todos los ms en minikube
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"  # La ruta que configuraste en Django (urls.py)
    prometheus.io/port: "8004"    # El puerto en el que tu app Django corre DENTRO del pod y expone /metrics
  #------- y aplicarlo con kubectl apply -f service.yaml dentro de la carpeta ms-invetairo
spec:
  type: ClusterIP
  selector:
    app: ms-usuariocliente
  ports:
    - protocol: TCP
      port: 8004
      targetPort: 8000
  # loadbalancer
