apiVersion: v1
kind: Service
metadata:
  name: ms-venta
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: ms-venta
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005

