apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-inventario-front
  namespace: ms-inventario-front
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ms-inventario-front
                port:
                  number: 80