apiVersion: v1
kind: Service
metadata:
  name: ms-trabajador
  namespace: backend
spec:
  type: ClusterIP 
  selector:
    app: ms-trabajador
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30083