apiVersion: v1
kind: Service
metadata:
  name: db-farmacia-farmacia
  namespace: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-farmacia