apiVersion: v1
kind: Service
metadata:
  name: ms-inventario-svc
  namespace: backend
  #agregar esto a todos los ms en minikube
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"  # La ruta que configuraste en Django (urls.py)
    prometheus.io/port: "8002"    # El puerto en el que tu app Django corre DENTRO del pod y expone /metrics
  #------- y aplicarlo con kubectl apply -f service.yaml dentro de la carpeta ms-invetairo
spec:
  type: ClusterIP
  selector:
    app: ms-inventario
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8000
