apiVersion: v1
kind: Service
metadata:
  name: ms-farmacia
  namespace: backend
spec:
  type: NodePort 
  selector:
    app: ms-farmacia
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006
      nodePort: 30086